### ISSUE TITLE
Address service account token expiration issue

### ISSUE THREAD

**Issue by pmpaulino** [liatrio/aws-managed-services#42]
## Overview

The service account token expires every 30 days. So we need a solution to rotate the service account token. Here is some supporting documentation. We've landed on rotating the service account token every 23 days, however this is up for debate and the number of days before rotation should be easily configurable. If this process fails we need to be notified, so also investigate a notification mechanism.

https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_turn-on-for-other.html
https://devopstar.com/2023/02/25/automatic-api-key-rotation-for-amazon-managed-grafana/

## AC

- Service account token is automatically rotated every 23 days
- Number of days before rotation is configurable
- Investigate and document in confluence findings regarding potential notification mechanisms on token rotation failure
- Documentation in confluence is created/updated to reflect any new findings
- Manually validate this token rotation process

**Comment by adrielp** [comment]
@PaulHLiatrio  / @pmpaulino  - is this still needing to be done? are y'all going to be doing this one

**Comment by PaulHLiatrio** [comment]
We have adjusted the codebase so that instead of storing a long lived token and needing to rotate it on a regular basis; we instead have it set up to generate a new API token on the fly which expires after 3m. 

This was accomplished by using a lifecycle block in Terraform, and we set the create_before_destroy flag to true.

This ticket is no longer necessary.
